### ISSUE TITLE
User login with metamask

### ISSUE THREAD

**Issue by camelop** [CoLearn-Dev/colink-frontend-dev#9]
Migrated from: https://github.com/camelop/dds-dev/issues/38

[MetaMask](https://metamask.io/) provides a way for users to connect to the web3 app without trusting js in the webpage.

- Could we make our system MetaMask compatible?

**Comment by stneng** [comment]
https://github.com/CoLearn-Dev/colink-frontend-dev/commit/51389599f3d269a90659b5c1fd2c616bb6c5e29e
